/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.DisplayMode;
import java.awt.GraphicsEnvironment;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import models.DanhMucModel;

/**
 *
 * @author Admin
 */
public class HomeMainView extends javax.swing.JFrame {

    /**
     * Creates new form HomeMain
     */
    public HomeMainView() {
        setTitle("QUẢN LÝ TIỀN ĐIỆN");
        ImageIcon iconForm = new ImageIcon("C:\\Users\\ADMIN\\OneDrive\\Documents\\NetBeansProjects\\QuanLyTienDien\\src\\icons\\Icon_app.png");
        setIconImage(iconForm.getImage());
        initComponents();
        setMaximized(true);
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
    }


    public void setMaximized(boolean maximized) {
        if (maximized) {
            DisplayMode mode = this.getGraphicsConfiguration().getDevice().getDisplayMode();
            Insets insets = Toolkit.getDefaultToolkit().getScreenInsets(this.getGraphicsConfiguration());
            this.setMaximizedBounds(new Rectangle(
                    mode.getWidth() - insets.right - insets.left,
                    mode.getHeight() - insets.top - insets.bottom
            ));
            this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(JFrame.NORMAL);
        }
    }
    
    

    public JPanel getJpnThongTin() {
        return jpnThongTin;
    }

    public JLabel getLabThongTin() {
        return labThongTin;
    }

    public JPanel getJpnChiSoDien() {
        return jpnChiSoDien;
    }

    public JLabel getLabChiSoDien() {
        return labChiSoDien;
    }

    public JPanel getJpnThongKe() {
        return jpnThongKe;
    }

    public JLabel getLabThongKe() {
        return labThongKe;
    }

    public JPanel getJpnThanhToan() {
        return jpnDanhSachThanhToan;
    }

    public JLabel getLabThanhToan() {
        return labThanhToan;
    }

    public JPanel getJpnHoaDon() {
        return jpnQuanLyHoaDon;
    }

    public JLabel getLabHoaDon() {
        return labHoaDon;
    }

    public JPanel getJpnView() {
        return jpnView;
    }

    public JMenuItem getLabLogout() {
        return labLogout;
    }

    public JLabel getLabTaiKhoan() {
        return labTaiKhoan;
    }

    public JPanel getJpnTaiKhoan() {
        return jpnTaiKhoan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();
        jpnThongTin = new javax.swing.JPanel();
        labThongTin = new javax.swing.JLabel();
        jpnChiSoDien = new javax.swing.JPanel();
        labChiSoDien = new javax.swing.JLabel();
        jpnQuanLyHoaDon = new javax.swing.JPanel();
        labHoaDon = new javax.swing.JLabel();
        jpnDanhSachThanhToan = new javax.swing.JPanel();
        labThanhToan = new javax.swing.JLabel();
        jpnThongKe = new javax.swing.JPanel();
        labThongKe = new javax.swing.JLabel();
        jpnTaiKhoan = new javax.swing.JPanel();
        labTaiKhoan = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        labLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jpnView.setBackground(new java.awt.Color(255, 255, 255));
        jpnView.setMinimumSize(new java.awt.Dimension(1400, 0));
        jpnView.setPreferredSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );

        jpnThongTin.setBackground(new java.awt.Color(204, 204, 204));
        jpnThongTin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpnThongTin.setMinimumSize(new java.awt.Dimension(0, 90));
        jpnThongTin.setPreferredSize(new java.awt.Dimension(0, 90));

        labThongTin.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        labThongTin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/quan_Li.png"))); // NOI18N
        labThongTin.setText("QUẢN LÝ THÔNG TIN");

        javax.swing.GroupLayout jpnThongTinLayout = new javax.swing.GroupLayout(jpnThongTin);
        jpnThongTin.setLayout(jpnThongTinLayout);
        jpnThongTinLayout.setHorizontalGroup(
            jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongTinLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );
        jpnThongTinLayout.setVerticalGroup(
            jpnThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnChiSoDien.setBackground(new java.awt.Color(76, 175, 80));
        jpnChiSoDien.setMinimumSize(new java.awt.Dimension(0, 90));
        jpnChiSoDien.setPreferredSize(new java.awt.Dimension(0, 90));

        labChiSoDien.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        labChiSoDien.setForeground(new java.awt.Color(255, 255, 255));
        labChiSoDien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labChiSoDien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cap_nhat.png"))); // NOI18N
        labChiSoDien.setText("CẬP NHẬT CHỈ SỐ ĐIỆN");

        javax.swing.GroupLayout jpnChiSoDienLayout = new javax.swing.GroupLayout(jpnChiSoDien);
        jpnChiSoDien.setLayout(jpnChiSoDienLayout);
        jpnChiSoDienLayout.setHorizontalGroup(
            jpnChiSoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnChiSoDienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labChiSoDien, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jpnChiSoDienLayout.setVerticalGroup(
            jpnChiSoDienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnChiSoDienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labChiSoDien, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnQuanLyHoaDon.setBackground(new java.awt.Color(76, 175, 80));
        jpnQuanLyHoaDon.setMinimumSize(new java.awt.Dimension(0, 90));
        jpnQuanLyHoaDon.setPreferredSize(new java.awt.Dimension(0, 90));

        labHoaDon.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        labHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        labHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hoa_don.png"))); // NOI18N
        labHoaDon.setText("QUẢN LÝ HOÁ ĐƠN");

        javax.swing.GroupLayout jpnQuanLyHoaDonLayout = new javax.swing.GroupLayout(jpnQuanLyHoaDon);
        jpnQuanLyHoaDon.setLayout(jpnQuanLyHoaDonLayout);
        jpnQuanLyHoaDonLayout.setHorizontalGroup(
            jpnQuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLyHoaDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jpnQuanLyHoaDonLayout.setVerticalGroup(
            jpnQuanLyHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLyHoaDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jpnDanhSachThanhToan.setBackground(new java.awt.Color(76, 175, 80));
        jpnDanhSachThanhToan.setMinimumSize(new java.awt.Dimension(0, 90));
        jpnDanhSachThanhToan.setPreferredSize(new java.awt.Dimension(0, 90));

        labThanhToan.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        labThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        labThanhToan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/thanh_toan.png"))); // NOI18N
        labThanhToan.setText("DANH SÁCH THANH TOÁN");

        javax.swing.GroupLayout jpnDanhSachThanhToanLayout = new javax.swing.GroupLayout(jpnDanhSachThanhToan);
        jpnDanhSachThanhToan.setLayout(jpnDanhSachThanhToanLayout);
        jpnDanhSachThanhToanLayout.setHorizontalGroup(
            jpnDanhSachThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnDanhSachThanhToanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labThanhToan)
                .addGap(35, 35, 35))
        );
        jpnDanhSachThanhToanLayout.setVerticalGroup(
            jpnDanhSachThanhToanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDanhSachThanhToanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jpnThongKe.setBackground(new java.awt.Color(76, 175, 80));
        jpnThongKe.setMinimumSize(new java.awt.Dimension(0, 90));
        jpnThongKe.setPreferredSize(new java.awt.Dimension(0, 90));

        labThongKe.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        labThongKe.setForeground(new java.awt.Color(255, 255, 255));
        labThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/thong_ke.png"))); // NOI18N
        labThongKe.setText("THỐNG KÊ DOANH THU");

        javax.swing.GroupLayout jpnThongKeLayout = new javax.swing.GroupLayout(jpnThongKe);
        jpnThongKe.setLayout(jpnThongKeLayout);
        jpnThongKeLayout.setHorizontalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongKeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnThongKeLayout.setVerticalGroup(
            jpnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnTaiKhoan.setBackground(new java.awt.Color(76, 175, 80));
        jpnTaiKhoan.setMinimumSize(new java.awt.Dimension(0, 90));

        labTaiKhoan.setFont(new java.awt.Font("Candara", 0, 20)); // NOI18N
        labTaiKhoan.setForeground(new java.awt.Color(255, 255, 255));
        labTaiKhoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/baseline_admin_panel_settings_white_24dp.png"))); // NOI18N
        labTaiKhoan.setText("QUẢN LÝ TÀI KHOẢN");

        javax.swing.GroupLayout jpnTaiKhoanLayout = new javax.swing.GroupLayout(jpnTaiKhoan);
        jpnTaiKhoan.setLayout(jpnTaiKhoanLayout);
        jpnTaiKhoanLayout.setHorizontalGroup(
            jpnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTaiKhoanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnTaiKhoanLayout.setVerticalGroup(
            jpnTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(243, 242, 242));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Icon_app.png"))); // NOI18N
        jLabel1.setText("HỆ THỐNG QUẢN LÝ TIỀN ĐIỆN");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpnView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1880, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jpnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jpnChiSoDien, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(jpnQuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jpnDanhSachThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnChiSoDien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnQuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnDanhSachThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE))
        );

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Hệ thống");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu5.setMinimumSize(new java.awt.Dimension(100, 35));
        jMenu5.setPreferredSize(new java.awt.Dimension(100, 24));

        labLogout.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/logout-icon-16.png"))); // NOI18N
        labLogout.setText("Đăng xuất");
        labLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labLogoutMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                labLogoutMouseReleased(evt);
            }
        });
        labLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labLogoutActionPerformed(evt);
            }
        });
        jMenu5.add(labLogout);
        jMenu5.add(jSeparator1);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Cá nhân");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu6.setMinimumSize(new java.awt.Dimension(100, 35));
        jMenu6.setPreferredSize(new java.awt.Dimension(100, 24));

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Apps-preferences-desktop-user-password-icon-16.png"))); // NOI18N
        jMenuItem3.setText("Thông tin");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);
        jMenu6.add(jSeparator4);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon/Actions-document-edit-icon-16.png"))); // NOI18N
        jMenuItem5.setText("Thay đổi mật khẩu");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);
        jMenu6.add(jSeparator5);

        jMenuBar1.add(jMenu6);

        jMenu3.setText("Trợ giúp");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(100, 35));
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1905, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        thongtin tt = new thongtin();
        tt.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        changePass pas = new changePass();
        pas.setVisible(true);

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void labLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labLogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_labLogoutMouseClicked

    private void labLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labLogoutMouseExited
        // TODO add your handling code here:
        labLogout.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_labLogoutMouseExited

    private void labLogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labLogoutMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_labLogoutMouseReleased

    private void labLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labLogoutMouseEntered
        // TODO add your handling code here:
        labLogout.setForeground(Color.BLACK);
    }//GEN-LAST:event_labLogoutMouseEntered

    private void labLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_labLogoutActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPanel jpnChiSoDien;
    private javax.swing.JPanel jpnDanhSachThanhToan;
    private javax.swing.JPanel jpnQuanLyHoaDon;
    private javax.swing.JPanel jpnTaiKhoan;
    private javax.swing.JPanel jpnThongKe;
    private javax.swing.JPanel jpnThongTin;
    private javax.swing.JPanel jpnView;
    private javax.swing.JLabel labChiSoDien;
    private javax.swing.JLabel labHoaDon;
    private javax.swing.JMenuItem labLogout;
    private javax.swing.JLabel labTaiKhoan;
    private javax.swing.JLabel labThanhToan;
    private javax.swing.JLabel labThongKe;
    private javax.swing.JLabel labThongTin;
    // End of variables declaration//GEN-END:variables
}
